import { BadgeDollarSign, BarChart3, CheckCircle2, Clock3, PackageOpen, Store } from 'lucide-react'
import type { CampaignMetrics, MerchantCampaign, MerchantTab, Order } from '../app/types'
import { Button } from '../components/Button'

interface Props { tab: MerchantTab; campaign: MerchantCampaign; metrics: CampaignMetrics; order: Order | null; onTab: (tab: MerchantTab) => void; onUpdateCampaign: (values: Partial<Pick<MerchantCampaign, 'cashback' | 'minimumSpend' | 'dailyCap'>>) => void; onPublish: () => void; onPreparing: () => void; onReady: () => void; onDarren: () => void }

export function MerchantWorkspaceScreen({ tab, campaign, metrics, order, onTab, onUpdateCampaign, onPublish, onPreparing, onReady, onDarren }: Props) {
  const conversion = metrics.recommendations ? Math.round(metrics.attributedPayments / metrics.recommendations * 100) : 0
  const costPerPayment = metrics.attributedPayments ? metrics.cashbackCost / metrics.attributedPayments : 0
  return <div className="screen screen--merchant-workspace">
    <header className="merchant-workspace-header"><div><p className="eyebrow">Felicia’s merchant view</p><h1 data-screen-heading tabIndex={-1}>Chicken Rice</h1></div><span className="merchant-monogram">F</span></header>
    <div className="merchant-tabs" role="tablist" aria-label="Merchant workspace"><button role="tab" aria-selected={tab === 'setup'} onClick={() => onTab('setup')}>Offer</button><button role="tab" aria-selected={tab === 'orders'} onClick={() => onTab('orders')}>Orders{order ? <i>1</i> : null}</button><button role="tab" aria-selected={tab === 'results'} onClick={() => onTab('results')}>Results</button></div>
    {tab === 'setup' ? <section className="merchant-panel"><div className="merchant-panel-heading"><BadgeDollarSign size={24} aria-hidden="true" /><div><p className="eyebrow">Pre-approved and capped</p><h2>Lunch cashback</h2></div></div>
      <div className="campaign-controls"><label>Cashback ($)<input aria-label="Cashback amount" type="number" min="0.10" step="0.10" value={campaign.cashback} onChange={(event) => onUpdateCampaign({ cashback: Number(event.target.value) || .1 })} /></label><label>Minimum spend ($)<input aria-label="Minimum eligible spend" type="number" min="0" step="0.50" value={campaign.minimumSpend} onChange={(event) => onUpdateCampaign({ minimumSpend: Number(event.target.value) || 0 })} /></label><label>Daily cap<input aria-label="Daily redemption cap" type="number" min="1" step="1" value={campaign.dailyCap} onChange={(event) => onUpdateCampaign({ dailyCap: Number(event.target.value) || 1 })} /></label></div>
      <dl className="offer-rules"><div><dt>Campaign window</dt><dd>{campaign.window}</dd></div><div className="offer-rules__total"><dt>Maximum daily cost</dt><dd>${campaign.maximumDailyCost.toFixed(2)}</dd></div></dl>
      <p className="merchant-funding-note">Merchant-funded · Unused rewards cost nothing · Released only after an eligible NETS payment</p>
      <Button fullWidth onClick={onPublish} disabled={campaign.status === 'active'}>{campaign.status === 'active' ? 'Offer published' : 'Publish illustrative offer'}</Button></section> : null}
    {tab === 'orders' ? <section className="merchant-panel">{!order || order.status === 'pending-payment' ? <div className="empty-merchant-state"><PackageOpen size={38} aria-hidden="true" /><h2>No paid order yet</h2><p>An order appears only after an eligible NETS payment is confirmed.</p></div> : <article className="merchant-order-card"><div className="merchant-order-card__top"><span className={`order-status order-status--${order.status}`}>{order.status}</span><strong>{order.id}</strong></div><h2>Darren</h2><p>{order.itemName}</p><strong className="merchant-order-amount">{order.displayAmount} · Paid with NETS</strong>
        {order.status === 'paid' ? <Button fullWidth onClick={onPreparing}>Start preparing</Button> : null}{order.status === 'preparing' ? <Button fullWidth onClick={onReady}>Mark ready</Button> : null}{order.status === 'ready' || order.status === 'collected' ? <div className="order-ready-confirmation"><CheckCircle2 size={20} aria-hidden="true" /><span>{order.status === 'ready' ? 'Darren notified: ready for collection' : 'Order collected'}</span></div> : null}<p className="action-helper">Felicia controls preparation. No AI cooking-time promise.</p></article>}</section> : null}
    {tab === 'results' ? <section className="merchant-panel"><div className="merchant-panel-heading"><BarChart3 size={24} aria-hidden="true" /><div><p className="eyebrow">Illustrative MVP data</p><h2>Campaign results</h2></div></div>
      <div className="metrics-grid"><div><span>Recommended</span><strong>{metrics.recommendations}</strong></div><div><span>Accepted</span><strong>{metrics.accepted}</strong></div><div><span>Attributed payments</span><strong>{metrics.attributedPayments}</strong></div><div><span>Cashback cost</span><strong>${metrics.cashbackCost.toFixed(2)}</strong></div></div>
      <div className="metric-summary"><div><Clock3 size={18} aria-hidden="true" /><span>Offer-to-payment conversion</span><strong>{conversion}%</strong></div><div><Store size={18} aria-hidden="true" /><span>Cost per attributed payment</span><strong>${costPerPayment.toFixed(2)}</strong></div></div>
      <p className="attribution-disclaimer">Attribution, not proven incrementality. A controlled pilot is required to prove additional sales.</p></section> : null}
    <div className="merchant-return"><Button variant="ghost" fullWidth onClick={onDarren}>Return to Darren</Button></div>
  </div>
}
